# -*- coding: utf-8 -*-
"""EA1. Ejemplo_Ingestión de Datos desde un API.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TI_mPpxkbvILbnG4jcJgrdElKXPLpi51

**<span style="color:#809bd8">Curso:</span>** **Infraestructura y Arquitectura para Big Data - Ingeniería de Software y Datos**

**<span style="color:#809bd8">Tema:</span>** **Evidencia de Aprendizaje EA1**

**<span style="color:#809bd8">Grupo:</span>** **PREICA2601B010094**

**<span style="color:#809bd8">Estudiante:</span>** **Anderson Andres castrillon**

**<span style="color:#809bd8">Profesor:</span>** **Walter Hugo Arboleda Mazo**

**<span style="color:#809bd8">Universidad:</span>** **Institución Universitaria Digital de Antioquia – IUDIGITAL**

**<span style="color:#809bd8">Fecha:</span>** **03/03/2026**
"""

# pip install requests pandas openpyxl
# requests: libreria para la conexion a una API y obtener o llevar datos a esta.
# pandas: libreria de python para el analisis y manipulacion de datos.
# openpyxl: libreria de python para crear o leer datos de MS Excel (.CSV)

import requests # importacion de la libreria Requests para enviar peticion a la API https://jsonplaceholder.typicode.com/users
import sqlite3 # importacion de la interface para conexion y creacion de bases de datos SQLite3
import pandas as pd # importacion de Pandas, libreria para el analisis de datos en Python

# Definicion de la URL de la API para envio de peticion y recepcion de datos usando protocolo HTTP
# desde la API https://jsonplaceholder.typicode.com/
API_URL = "https://jsonplaceholder.typicode.com/users"


# Creacion de la funcion extraer_datos validandose codigo 200 (exito en la conexion) o codigo 404 (codigo de error en la conexion)
def extraer_datos(url):
    response = requests.get(url)
    if response.status_code == 200:
        return response.json()
    else:
        raise Exception(f"Error al conectar con la API: {response.status_code}")


# Creacion de la base de datos en SQLite3 "datosac_api.db"
# se realiza la conexion a dicha base de datos
# y se crea el "cursor" para "execute" el CREATE TABLE y el INSERT OR REPLACE INTO usuarios
def guardar_en_db(datos):
    conn = sqlite3.connect('datos_api.db')
    cursor = conn.cursor()

    # Creación de la tabla "usuarios" dentro de la base de datos "datos_api.db"
    # esta contiene los campos id, nombre, usuario y email
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS usuarios (
            id INTEGER PRIMARY KEY,
            nombre TEXT,
            usuario TEXT,
            email TEXT
        )
    ''')

    # Inserción de datos en la tabla "usuarios"
    for item in datos:
        cursor.execute('''
            INSERT OR REPLACE INTO usuarios (id, nombre, usuario, email)
            VALUES (?, ?, ?, ?)
        ''', (item['id'], item['name'], item['username'], item['email']))

    # Aceptación mediante "Commit" el ingreso de datos en la tabla "usuarios"
    conn.commit()

    # Cerrado de la conexion a la base de datos "datos_api.db"
    conn.close()

# 3. GENERAR EVIDENCIAS (Pandas y Auditoría)
def generar_evidencias(datos_api):
    # --- Archivo Excel/CSV con Pandas ---
    conn = sqlite3.connect('datos_api.db')

    # uso de pandas de los metodos read_sql_query() y to_csv()
    df_db = pd.read_sql_query("SELECT * FROM usuarios", conn)
    df_db.to_csv('muestra_usuarios.csv', index=False)
    conn.close()

    # la variable "registros_api" obtiene la cantidad de registros recibidos desde la
    # API con url "https://jsonplaceholder.typicode.com/users"
    # la variable "registros_db" obtiene la cantidad de registros almacenados en la tabla "usuarios"
    registros_api = len(datos_api)
    registros_db = len(df_db)

    # Creación del archivo "auditoría.txt" con el metodo "open" de Python
    with open('auditoria.txt', 'w', encoding='utf-8') as f:
        f.write("RESUMEN DE AUDITORÍA\n")
        f.write("====================\n")
        f.write(f"Registros extraídos de la API https://jsonplaceholder.typicode.com/users: {registros_api}\n")
        f.write(f"Registros guardados en la DB de SQLite3: {registros_db}\n")

        if registros_api == registros_db:
            f.write("\nESTADO: Operacion Exitosa.\n")
        else:
            f.write("\nESTADO: Operacion Fallida.\n")

# EJECUCIÓN DEL PROCESO
try:
    print("Iniciando proceso de petición y recepción de datos desde la API https://jsonplaceholder.typicode.com/users...")
    datos = extraer_datos(API_URL)

    print("Creando la base de datos datos_api.db y guardando datos en la tabla usuarios...")
    guardar_en_db(datos)

    print("Generando archivos de evidencia .CSV y auditoría.txt...")
    generar_evidencias(datos)

    print("¡Proceso completado con éxito!")
except Exception as e:
    print(f"Ocurrió un error: {e}")



"""
**Referencias**

https://realpython.com/python-requests/#make-a-get-request

https://pandas.pydata.org/

https://pypi.org/project/openpyxl/

https://docs.python.org/3/library/sqlite3.html

https://sqliteviewer.app/

https://sibabalwesinyaniso.medium.com/what-is-a-cursor-understanding-how-sqlite-handles-queries-in-python-8f8c88546820
https://www.pythonlore.com/understanding-sqlite3-cursor-object-for-database-operations/
https://miro.medium.com/v2/resize:fit:720/format:webp/0*rePKZ6jMZbZ_6S_3.gif

https://pytutorial.com/python-sqlite3-database-connection-guide/

"""



